### ISSUE TITLE
无法上传图片到自建Danbooru

### ISSUE THREAD

**Issue by xperiazu21** [charlie0129/booru-scripts#1]
运行`make get_favorites_and_sync_to_danbooru`指令，程序运作到upload-images-from-dir.js时，返回status code 408错误。

但使用cURL进行上传测试是正常的。

**Comment by charlie0129** [comment]
我测试可以正常上传 
<img width="435" alt="image" src="https://github.com/charlie0129/booru-scripts/assets/55270174/1741ad11-e5f9-4cd0-a831-84013232dd22">

如果网络环境都正常，也许和 danbooru 版本有关（我目前在使用 17 个月前的版本），我不确定是否 danbooru 后续更改了 API

**Comment by xperiazu21** [comment]
感谢回复
我是几天前才使用docker安装，版本如下图
![image](https://github.com/charlie0129/booru-scripts/assets/53937642/aa342ddb-e32a-4d0e-811f-aee8f4f17f4b)

尝试了网上将cURL转Axios的网站，想说运行成功后再修改原来程序，但是仍然报错。

还测试了以source方式给moebooru网址方式。 此方式是正常的，因此猜测是上传图片部分的程式码需要修改。

**Comment by charlie0129** [comment]
Thank you for your information. 后续有时间我会测试一下最新版本的 danbooru 是否可以上传（最近比较忙x）

**Comment by charlie0129** [comment]
下载最新版本的代码看看是否修复了该问题？

**Comment by xperiazu21** [comment]
更新代码后，已经可以正常上传图片了。
也测试了`make get-and-update-tags-all`，工作正常。
感谢您的迅速修复!
